name: TestWorkflow

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3

